### ISSUE TITLE
Mutating State

### ISSUE THREAD

**Issue by sjlagasse** [sthlmj/jammming#1]
Inside of App.js you mutate state when you do:

line 35-36:

```
let tracks = this.state.playlistTracks
tracks.push(track)
```

This is because `tracks` is a direct reference to `this.state.playlistTracks`. Meaning, anything you do to `tracks` will happen to `this.state.playlistTracks`. In order to make a copy of state use `.slice` or the `spread operator`.

e.g.
```
const tracks = this.state.playlistTracks.slice();
const tracks = [ ...this.state.playlistTracks ];
```

The same can be said about your `removeTrack` function.

**Comment by sthlmj** [comment]
@sjlagasse thanks!
